// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5DIosaCZsrSOtUGWCuWwi6W0d3-ZHJKk',
    appId: '1:1006459494712:web:0df64402c503ccbec561cd',
    messagingSenderId: '1006459494712',
    projectId: 'customtimer-fe3a9',
    authDomain: 'customtimer-fe3a9.firebaseapp.com',
    storageBucket: 'customtimer-fe3a9.appspot.com',
    measurementId: 'G-QEKSH4YBN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGBxcoS3LuZ2EIM8er31UOq2A8z9exDs',
    appId: '1:1006459494712:android:f272fc8409c1843cc561cd',
    messagingSenderId: '1006459494712',
    projectId: 'customtimer-fe3a9',
    storageBucket: 'customtimer-fe3a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULQSzdaTE7EKXYVADdRvKBjO_kKGh7-k',
    appId: '1:1006459494712:ios:331f6efa949eaaffc561cd',
    messagingSenderId: '1006459494712',
    projectId: 'customtimer-fe3a9',
    storageBucket: 'customtimer-fe3a9.appspot.com',
    iosBundleId: 'com.example.customTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBULQSzdaTE7EKXYVADdRvKBjO_kKGh7-k',
    appId: '1:1006459494712:ios:331f6efa949eaaffc561cd',
    messagingSenderId: '1006459494712',
    projectId: 'customtimer-fe3a9',
    storageBucket: 'customtimer-fe3a9.appspot.com',
    iosBundleId: 'com.example.customTimer',
  );
}
